### ISSUE TITLE
TIP: next.config doesn't have to be a cjs file

### ISSUE THREAD

**Issue by Kr33L** [fac26/week7-9-ArtBadge#24]
The reason it was always throwing an error is because it's exporting with module.exports, which can be changed to export default. Just a minor thing I found today, but I guess it's useful for the sake of consistency.
Instead of 
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig
```
use
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
	reactStrictMode: true
};

export default nextConfig;
```

**Comment by Kr33L** [comment]
![](https://media4.giphy.com/media/m9eG1qVjvN56H0MXt8/giphy.gif?cid=ecf05e473nr2b5hrqqqzl527oa54a0m8vweoi687k8yjaof2&rid=giphy.gif&ct=g)

**Comment by LauraK0** [comment]
Useful tip, great gif

**Comment by Psydwinder** [comment]
Man like Karol is faster than Sonic

![image](https://user-images.githubusercontent.com/101563800/223079388-4584adcd-d2e4-4f32-b969-d69df63f0037.png)
