### ISSUE TITLE
The whole supabaseClient file is (probably) redundant

### ISSUE THREAD

**Issue by Kr33L** [fac26/week7-9-ArtBadge#45]
We are able to make database queries without createClient, only with useSupabaseClient. In this file: https://github.com/fac26/goth-kking/blob/main/src/components/CreateSpace.js

Not sure what your problem was with module exports, maybe Niete is confused with the next config which is the only mention of module.exports. (just noticed it's not using module.exports but the file is still .cjs so maybe that could be something.)

**Comment by Psydwinder** [comment]
This has now been resolved
