### ISSUE TITLE
Supabase Settings change to prevent default option (localhost)

### ISSUE THREAD

**Issue by konstantinakatmada** [fac26/week7-9-ArtBadge#50]
As is, when I am clicking on the email sent from supabase to confirm my email, the "Confirm your email" link is directing me to the localhost. Even after clearing, the page is not appearing, so that the Sign up can be completed. This can be solved by changing the Supabase settings to link to the deployed page in place of local host.

**Comment by LauraK0** [comment]
Thanks this has been updated.
